version: "3.6"

services:

  database:
    image: <$DTR_HOST>/backend/database
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
    ports:
      - "3306:3306"
    networks:
      - back-tier
    secrets:
      - mysql_root_password

  webserver:
    image: <$DTR_HOST>/frontend/java_web:2
    ports:
      - "8080:8080"
    environment:
      BASEURI: http://messageservice:8090/user
    networks:
      - front-tier
      - back-tier

  signup_client:
    image:  <$DTR_HOST>/frontend/signup_client
    ports:
      - "8000:80"
    environment:
      BASEURI: http://messageservice:8090/user
    networks: 
      - front-tier
      - back-tier

  messageservice:
    image: <$DTR_HOST>/backend/messageservice
    ports:
      - "8090:8090"
    networks:
      - back-tier

  worker:
    image: <$DTR_HOST>/backend/worker:1
    networks:
      - back-tier

  redis:
    image: redis
    ports: 
      - "6379:6379"
    networks:
      - back-tier

networks:
  front-tier:
    external : true
  back-tier:
    external : true

secrets:
  mysql_root_password:
    external: true