apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-05-16T22:14:05Z
  labels:
    com.docker.service.id: java-web-5-redis
    com.docker.service.name: redis
    com.docker.stack.namespace: java-web-5
  name: redis
  namespace: default
  ownerReferences:
  - apiVersion: compose.docker.com/v1beta2
    blockOwnerDeletion: true
    controller: true
    kind: Stack
    name: java-web-5
    uid: 720af4c8-5956-11e8-a920-025000000001
  resourceVersion: "2749504"
  selfLink: /api/v1/namespaces/default/services/redis
  uid: 7260db0f-5956-11e8-b1d2-025000000001
spec:
  clusterIP: None
  ports:
  - name: headless
    port: 55555
    protocol: TCP
    targetPort: 55555
  selector:
    com.docker.service.id: java-web-5-redis
    com.docker.service.name: redis
    com.docker.stack.namespace: java-web-5
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
