version: "3.3"

services:

  database:
    image: database
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306" 
    networks:
      - back-tier

  webserver:
    image:  java_web:2
    environment:
      BASEURI: http://messageservice:8090/user
    ports:
      - "8080:8080" 
    networks:
      - front-tier
      - back-tier
  
  signup_client:
    image:  signup_client
    environment:
      REACT_APP_MESSAGESERVICE_URI: http://messageservice:8090/user
    ports:
      - "8000:80"
    networks: 
      - front-tier
      - back-tier

  messageservice:
    image: messageservice
    ports:
      - "8090:8090"
    networks: 
      - back-tier

  worker:
    image: worker
    networks: 
      - back-tier

  redis:
    image: redis
    container_name: redis
    ports: 
      - "6379:6379"
    networks:
      - back-tier

networks:
  front-tier:
  back-tier: